name: deploy this repo

on: push

jobs:
  format-code:
    # runs-on:
    permissions:
      contents: write
    steps:
      - uses: actions/checkout@v3
      - uses: stefanzweifel/git-auto-commit-action@v4
